//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente_Rutina
    {
        public int IdCliente { get; set; }
        public Nullable<int> idRutinas { get; set; }
    
        public virtual Detalle_Cliente Detalle_Cliente { get; set; }
        public virtual Rutina Rutina { get; set; }
    }
}
